CREATE TABLE flights
(
  id                         UUID PRIMARY KEY         DEFAULT uuid_generate_v4(),
  flight_date                varchar(10),
  flight_status              varchar(255) CHECK (
    flight_status IN (
                      'scheduled',
                      'active',
                      'landed',
                      'canceled',
                      'incident',
                      'diverted'
      )
    ),
  departure_airport          varchar(70),
  departure_timezone         varchar(70),
  departure_iata             varchar(10),
  departure_icao             varchar(10),
  departure_terminal         varchar(10),
  departure_gate             varchar(10),
  departure_delay            int,
  departure_scheduled        timestamp,
  departure_estimated        timestamp,
  departure_actual           timestamp,
  departure_estimated_runway timestamp,
  departure_actual_runway    timestamp,
  arrival_airport            varchar(70),
  arrival_timezone           varchar(70),
  arrival_iata               varchar(10),
  arrival_icao               varchar(10),
  arrival_terminal           varchar(10),
  arrival_gate               varchar(10),
  arrival_baggage            varchar(10),
  arrival_delay              int,
  arrival_scheduled          timestamp,
  arrival_estimated          timestamp,
  arrival_actual             timestamp,
  arrival_estimated_runway   timestamp,
  arrival_actual_runway      timestamp,
  airline_id                 UUID REFERENCES airline (id),
  airline_name               varchar(100),
  airline_iata               varchar(10),
  airline_icao               varchar(10),
  flight_number              varchar(10),
  flight_iata                varchar(10),
  flight_icao                varchar(10),
  codeshared_airline_name    varchar(255),
  codeshared_airline_iata    varchar(255),
  codeshared_airline_icao    varchar(255),
  codeshared_flight_number   varchar(255),
  codeshared_flight_iata     varchar(255),
  codeshared_flight_icao     varchar(255),
  aircraft_registration      varchar(10),
  aircraft_iata              varchar(10),
  aircraft_icao              varchar(10),
  aircraft_icao24            varchar(10),
  live_updated               varchar(100),
  live_latitude              float,
  live_longitude             float,
  live_altitude              int,
  live_direction             int,
  live_speed_horizontal      int,
  live_speed_vertical        int,
  live_is_ground             bool,
  created_at                 TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

--
