CREATE TABLE flights (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  flight_date varchar(10),
  flight_status varchar(255) CHECK (
    flight_status IN (
      'scheduled',
      'active',
      'landed',
      'cancelled',
      'incident',
      'diverted'
    )
  ),
  departure_airport varchar(255),
  departure_timezone varchar(255),
  departure_iata varchar(255),
  departure_icao varchar(255),
  departure_terminal varchar(255),
  departure_gate varchar(255),
  departure_delay int,
  departure_scheduled varchar(25),
  departure_estimated varchar(25),
  departure_actual varchar(25),
  departure_estimated_runway varchar(25),
  departure_actual_runway varchar(25),
  arrival_airport varchar(255),
  arrival_timezone varchar(255),
  arrival_iata varchar(255),
  arrival_icao varchar(255),
  arrival_terminal varchar(255),
  arrival_gate varchar(255),
  arrival_baggage varchar(255),
  arrival_delay int,
  arrival_scheduled varchar(25),
  arrival_estimated varchar(25),
  arrival_actual varchar(25),
  arrival_estimated_runway varchar(25),
  arrival_actual_runway varchar(25),
  airline_id UUID REFERENCES airline(id),
  flight_number varchar(10),
  flight_iata varchar(10),
  flight_icao varchar(10),
  codeshared_airline_name varchar(255),
  codeshared_airline_iata varchar(255),
  codeshared_airline_icao varchar(255),
  codeshared_flight_number varchar(255),
  codeshared_flight_iata varchar(255),
  codeshared_flight_icao varchar(255),
  aircraft_registration varchar(10),
  aircraft_iata varchar(10),
  aircraft_icao varchar(10),
  aircraft_icao25 varchar(10),
  live_updated varchar(50),
  live_latitude float,
  live_longitude float,
  live_altitude int,
  live_direction int,
  live_speed_horizontal int,
  live_speed_vertical int,
  live_is_ground bool,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW ()
);

--
